import mongoose from 'mongoose';


const Schema = mongoose.Schema;

const TodoSchema = new Schema({
    // id will be automatically generated by MongoDB
    // id format: 24-character hexcadecimal string (0-9, a-f)
    title: { type: String, maxlength: 25, required: true },
    description: { type: String, maxlength: 255, required: true },
    status: { type: String, default: "NOT DONE" },
    timestamp: { type: Date, default: Date.now }
});

const Todo = mongoose.model("Todo", TodoSchema);


export default Todo;
